-- GENERATED by `lineupiq snowflake ddl`. Do not edit by hand.
--
-- Every column and type below is derived from the committed data contract in
-- data/gold/_contracts/, which is itself derived from the parquet on disk. That
-- is what makes the local layer and this DDL incapable of drifting apart: there
-- is one description of the schema and two consumers of it.
--
-- Nothing here is on the demo path. LineupIQ runs, tests and verifies with no
-- Snowflake account; this adapter exists so the same `SELECT * FROM
-- GOLD.SHOT_FACTS` is valid in both places.


CREATE DATABASE IF NOT EXISTS LINEUPIQ;

USE DATABASE LINEUPIQ;

CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS ML;

-- An XSMALL warehouse with aggressive auto-suspend. The whole point of
-- the portable core is that this adapter never has to be running, so a
-- warehouse left on is pure waste.
--
-- Continuation lines are not indented: sqlfluff's Snowflake dialect reads
-- indented warehouse properties as a nested block and reports LT02.
CREATE WAREHOUSE IF NOT EXISTS LINEUPIQ_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

-- A hard credit ceiling. Without a resource monitor a runaway query on a
-- trial account is a silent invoice, which is the specific failure mode
-- that made this project treat Snowflake as optional in the first place.
--
-- The parser check is suppressed for this statement only. sqlfluff's
-- Snowflake dialect does not implement CREATE RESOURCE MONITOR at all --
-- verified against the minimal one-line form, which also fails to parse.
-- The syntax below is Snowflake's documented form. The suppression is
-- scoped to these lines rather than the file, so every other statement
-- here is still parsed.
-- noqa: disable=PRS
CREATE RESOURCE MONITOR IF NOT EXISTS LINEUPIQ_MONITOR
WITH CREDIT_QUOTA = 20
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS ON 90 PERCENT DO NOTIFY
ON 100 PERCENT DO SUSPEND;
-- noqa: enable=PRS

ALTER WAREHOUSE LINEUPIQ_WH SET RESOURCE_MONITOR = LINEUPIQ_MONITOR;
