-- GENERATED by `lineupiq snowflake ddl`. Do not edit by hand.
--
-- Every column and type below is derived from the committed data contract in
-- data/gold/_contracts/, which is itself derived from the parquet on disk. That
-- is what makes the local layer and this DDL incapable of drifting apart: there
-- is one description of the schema and two consumers of it.
--
-- Nothing here is on the demo path. LineupIQ runs, tests and verifies with no
-- Snowflake account; this adapter exists so the same `SELECT * FROM
-- GOLD.SHOT_FACTS` is valid in both places.


USE DATABASE LINEUPIQ;

USE SCHEMA GOLD;

-- dim_player: 541 rows in the committed season=2022 partition.
CREATE TABLE IF NOT EXISTS DIM_PLAYER (
    PLAYER_ID NUMBER(38, 0),
    PLAYER_NAME VARCHAR
);

-- possession_facts: 259,960 rows in the committed season=2022 partition.
CREATE TABLE IF NOT EXISTS POSSESSION_FACTS (
    GAME_ID VARCHAR,
    PERIOD NUMBER(38, 0),
    POSSESSION_NUMBER NUMBER(38, 0),
    NUMBER_IN_PERIOD NUMBER(38, 0),
    OFFENSE_TEAM_ID NUMBER(38, 0),
    DEFENSE_TEAM_ID NUMBER(38, 0),
    POSSESSION_START_CLOCK FLOAT,
    FIRST_EVENT_SECONDS_REMAINING FLOAT,
    END_SECONDS_REMAINING FLOAT,
    POSSESSION_SECONDS FLOAT,
    POINTS NUMBER(38, 0),
    POSSESSION_START_TYPE VARCHAR,
    IS_SECOND_CHANCE BOOLEAN,
    FG2A NUMBER(38, 0),
    FG3A NUMBER(38, 0),
    FTA NUMBER(38, 0),
    TOV NUMBER(38, 0),
    OREB NUMBER(38, 0),
    STINT_INDEX NUMBER(38, 0),
    HOME_LINEUP ARRAY,
    AWAY_LINEUP ARRAY,
    STINT_QUALITY VARCHAR,
    HOME_TEAM_ID NUMBER(38, 0),
    ORACLE_OFF_LINEUP ARRAY,
    OFF_LINEUP ARRAY,
    DEF_LINEUP ARRAY,
    OFF_LINEUP_HASH VARCHAR,
    DEF_LINEUP_HASH VARCHAR,
    LIVE_BALL_START BOOLEAN,
    BOUNDARY_AMBIGUOUS BOOLEAN,
    SEASON NUMBER(38, 0),
    TRANSITION BOOLEAN
);

-- shot_facts: 231,869 rows in the committed season=2022 partition.
CREATE TABLE IF NOT EXISTS SHOT_FACTS (
    GAME_ID VARCHAR,
    EVENT_NUM NUMBER(38, 0),
    SHOOTER_ID NUMBER(38, 0),
    TEAM_ID NUMBER(38, 0),
    PERIOD NUMBER(38, 0),
    SECONDS_REMAINING NUMBER(38, 0),
    LOC_X FLOAT,
    LOC_Y FLOAT,
    SHOT_DISTANCE_FT FLOAT,
    ACTION_TYPE VARCHAR,
    SHOT_TYPE_RAW VARCHAR,
    FEED_ZONE_BASIC VARCHAR,
    MADE NUMBER(38, 0),
    ZONE_ID VARCHAR,
    IS_THREE BOOLEAN,
    SEASON NUMBER(38, 0),
    SHOT_POINTS NUMBER(38, 0),
    HOME_LINEUP ARRAY,
    AWAY_LINEUP ARRAY,
    LINEUP_QUALITY VARCHAR,
    LINEUP_METHOD VARCHAR,
    LINEUP_FOR ARRAY,
    LINEUP_AGAINST ARRAY,
    STINT_QUALITY VARCHAR,
    LINEUP_FOR_HASH VARCHAR,
    LINEUP_AGAINST_HASH VARCHAR
);

-- stints: 39,320 rows in the committed season=2022 partition.
CREATE TABLE IF NOT EXISTS STINTS (
    GAME_ID VARCHAR,
    PERIOD NUMBER(38, 0),
    STINT_INDEX NUMBER(38, 0),
    START_SECONDS_REMAINING NUMBER(38, 0),
    END_SECONDS_REMAINING NUMBER(38, 0),
    DURATION_SECONDS NUMBER(38, 0),
    HOME_LINEUP ARRAY,
    AWAY_LINEUP ARRAY,
    STINT_QUALITY VARCHAR
);
