-- GENERATED by `lineupiq snowflake ddl`. Do not edit by hand.
--
-- Every column and type below is derived from the committed data contract in
-- data/gold/_contracts/, which is itself derived from the parquet on disk. That
-- is what makes the local layer and this DDL incapable of drifting apart: there
-- is one description of the schema and two consumers of it.
--
-- Nothing here is on the demo path. LineupIQ runs, tests and verifies with no
-- Snowflake account; this adapter exists so the same `SELECT * FROM
-- GOLD.SHOT_FACTS` is valid in both places.


USE DATABASE LINEUPIQ;

USE SCHEMA ML;

-- player_rapm: 770 rows in the committed pooled partition.
CREATE TABLE IF NOT EXISTS PLAYER_RAPM (
    PLAYER_ID NUMBER(38, 0),
    OFF_RAPM FLOAT,
    DEF_RAPM FLOAT,
    TOTAL_RAPM FLOAT,
    OFF_SE FLOAT,
    DEF_SE FLOAT,
    OFF_INCLUDES_ZERO BOOLEAN,
    DEF_INCLUDES_ZERO BOOLEAN,
    POSSESSIONS NUMBER(38, 0)
);
