-- GENERATED by `lineupiq snowflake ddl`. Do not edit by hand.
--
-- Every column and type below is derived from the committed data contract in
-- data/gold/_contracts/, which is itself derived from the parquet on disk. That
-- is what makes the local layer and this DDL incapable of drifting apart: there
-- is one description of the schema and two consumers of it.
--
-- Nothing here is on the demo path. LineupIQ runs, tests and verifies with no
-- Snowflake account; this adapter exists so the same `SELECT * FROM
-- GOLD.SHOT_FACTS` is valid in both places.


-- Drops everything this adapter created. Present so that trying the
-- adapter is reversible in one statement rather than a cleanup task.
DROP DATABASE IF EXISTS LINEUPIQ;

DROP WAREHOUSE IF EXISTS LINEUPIQ_WH;

DROP RESOURCE MONITOR IF EXISTS LINEUPIQ_MONITOR;
