"""One schema registry, two engines.

The Snowflake DDL is **generated from the committed data contracts**, not typed
by hand. That is the whole point of this module: a contract already records
every gold table's columns and dtypes as they actually are on disk, so
generating the DDL from it makes schema drift impossible rather than merely
discouraged. Hand-maintaining a parallel `.sql` file is how a repository ends up
with pretty SQL that does not match its data.

The mapping from polars dtypes to Snowflake types is deliberately narrow. Every
entry is a type this project actually uses; an unknown dtype raises rather than
falling back to VARCHAR, because a silent VARCHAR column is a load that succeeds
and a query that is quietly wrong.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from lineupiq.paths import DataPaths

__all__ = [
    "SNOWFLAKE_TYPES",
    "TableSpec",
    "generate_snowflake_ddl",
    "load_specs",
    "schema_parity_problems",
]

#: polars dtype name -> Snowflake column type.
#:
#: ``List(Int64)`` becomes ARRAY, which is where the lineup-hash parity risk
#: lives: Snowflake's ``ARRAY_SORT`` on a VARIANT array sorts lexicographically
#: unless told otherwise, and a lexicographic sort of player ids produces a
#: different hash than the numeric sort used everywhere else. The integration
#: test exists to catch exactly that; see docs/modeling.md.
SNOWFLAKE_TYPES: dict[str, str] = {
    "Int64": "NUMBER(38, 0)",
    "Int32": "NUMBER(38, 0)",
    "Float64": "FLOAT",
    "Float32": "FLOAT",
    "String": "VARCHAR",
    "Boolean": "BOOLEAN",
    "List(Int64)": "ARRAY",
    "List(String)": "ARRAY",
}

#: Which schema each table belongs in.
_SCHEMA_OF: dict[str, str] = {
    "shot_facts": "GOLD",
    "stints": "GOLD",
    "dim_player": "GOLD",
    "possession_facts": "GOLD",
    "player_rapm": "ML",
}


@dataclass(frozen=True)
class TableSpec:
    """One table, as the committed contract describes it."""

    table: str
    partition: str
    schema: str
    columns: list[str]
    dtypes: dict[str, str]
    rows: int

    @property
    def qualified(self) -> str:
        return f"{self.schema}.{self.table.upper()}"

    def snowflake_columns(self) -> list[tuple[str, str]]:
        out: list[tuple[str, str]] = []
        for name in self.columns:
            dtype = self.dtypes[name]
            if dtype not in SNOWFLAKE_TYPES:
                raise KeyError(
                    f"{self.table}.{name} has polars dtype {dtype!r} with no Snowflake "
                    "mapping. Add one to SNOWFLAKE_TYPES rather than letting it default "
                    "to VARCHAR."
                )
            out.append((name.upper(), SNOWFLAKE_TYPES[dtype]))
        return out


def load_specs(paths: DataPaths) -> list[TableSpec]:
    """Read every committed contract and turn it into a table spec.

    Partitions of the same table share a schema, so only the first partition of
    each table is kept -- the DDL describes one table, not one per season.
    """
    seen: dict[str, TableSpec] = {}
    if not paths.contracts.exists():
        return []
    for path in sorted(paths.contracts.glob("*.json")):
        stored = json.loads(path.read_text(encoding="utf-8"))
        table = stored["table"]
        if table in seen:
            continue
        seen[table] = TableSpec(
            table=table,
            partition=stored["partition"],
            schema=_SCHEMA_OF.get(table, "GOLD"),
            columns=list(stored["columns"]),
            dtypes=dict(stored["dtypes"]),
            rows=int(stored["rows"]),
        )
    return list(seen.values())


_HEADER = """-- GENERATED by `lineupiq snowflake ddl`. Do not edit by hand.
--
-- Every column and type below is derived from the committed data contract in
-- data/gold/_contracts/, which is itself derived from the parquet on disk. That
-- is what makes the local layer and this DDL incapable of drifting apart: there
-- is one description of the schema and two consumers of it.
--
-- Nothing here is on the demo path. LineupIQ runs, tests and verifies with no
-- Snowflake account; this adapter exists so the same `SELECT * FROM
-- GOLD.SHOT_FACTS` is valid in both places.
"""


def generate_snowflake_ddl(specs: list[TableSpec]) -> dict[str, str]:
    """Emit the DDL files. Returns ``{filename: contents}``."""
    files: dict[str, str] = {}

    schemas = sorted({spec.schema for spec in specs})
    account = [
        _HEADER,
        "",
        "CREATE DATABASE IF NOT EXISTS LINEUPIQ;",
        "",
        "USE DATABASE LINEUPIQ;",
        "",
    ]
    for schema in schemas:
        account.append(f"CREATE SCHEMA IF NOT EXISTS {schema};")
    account += [
        "",
        "-- An XSMALL warehouse with aggressive auto-suspend. The whole point of",
        "-- the portable core is that this adapter never has to be running, so a",
        "-- warehouse left on is pure waste.",
        "--",
        "-- Continuation lines are not indented: sqlfluff's Snowflake dialect reads",
        "-- indented warehouse properties as a nested block and reports LT02.",
        "CREATE WAREHOUSE IF NOT EXISTS LINEUPIQ_WH",
        "WAREHOUSE_SIZE = 'XSMALL'",
        "AUTO_SUSPEND = 60",
        "AUTO_RESUME = TRUE",
        "INITIALLY_SUSPENDED = TRUE;",
        "",
        "-- A hard credit ceiling. Without a resource monitor a runaway query on a",
        "-- trial account is a silent invoice, which is the specific failure mode",
        "-- that made this project treat Snowflake as optional in the first place.",
        "--",
        "-- The parser check is suppressed for this statement only. sqlfluff's",
        "-- Snowflake dialect does not implement CREATE RESOURCE MONITOR at all --",
        "-- verified against the minimal one-line form, which also fails to parse.",
        "-- The syntax below is Snowflake's documented form. The suppression is",
        "-- scoped to these lines rather than the file, so every other statement",
        "-- here is still parsed.",
        "-- noqa: disable=PRS",
        "CREATE RESOURCE MONITOR IF NOT EXISTS LINEUPIQ_MONITOR",
        "WITH CREDIT_QUOTA = 20",
        "FREQUENCY = MONTHLY",
        "START_TIMESTAMP = IMMEDIATELY",
        "TRIGGERS ON 90 PERCENT DO NOTIFY",
        "ON 100 PERCENT DO SUSPEND;",
        "-- noqa: enable=PRS",
        "",
        "ALTER WAREHOUSE LINEUPIQ_WH SET RESOURCE_MONITOR = LINEUPIQ_MONITOR;",
        "",
    ]
    files["000_account_setup.sql"] = "\n".join(account)

    for schema in schemas:
        members = sorted(
            (spec for spec in specs if spec.schema == schema), key=lambda spec: spec.table
        )
        lines = [_HEADER, "", "USE DATABASE LINEUPIQ;", "", f"USE SCHEMA {schema};", ""]
        for spec in members:
            lines.append(
                f"-- {spec.table}: {spec.rows:,} rows in the committed {spec.partition} partition."
            )
            lines.append(f"CREATE TABLE IF NOT EXISTS {spec.table.upper()} (")
            # One space between name and type. Aligning the types reads better,
            # but `sqlfluff lint --dialect snowflake` flags it as LT01, and a
            # linter that has to be silenced for cosmetics is a linter nobody
            # trusts when it flags something real.
            body = [f"    {name} {kind}" for name, kind in spec.snowflake_columns()]
            lines.append(",\n".join(body))
            lines.append(");")
            lines.append("")
        index = "030_gold.sql" if schema == "GOLD" else "040_ml.sql"
        files[index] = "\n".join(lines)

    files["090_teardown.sql"] = "\n".join(
        [
            _HEADER,
            "",
            "-- Drops everything this adapter created. Present so that trying the",
            "-- adapter is reversible in one statement rather than a cleanup task.",
            "DROP DATABASE IF EXISTS LINEUPIQ;",
            "",
            "DROP WAREHOUSE IF EXISTS LINEUPIQ_WH;",
            "",
            "DROP RESOURCE MONITOR IF EXISTS LINEUPIQ_MONITOR;",
            "",
        ]
    )
    return files


def write_snowflake_ddl(paths: DataPaths, files: dict[str, str]) -> list[Path]:
    directory = paths.sql_snowflake
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, contents in sorted(files.items()):
        path = directory / name
        path.write_text(contents.rstrip() + "\n", encoding="utf-8", newline="\n")
        written.append(path)
    return written


def schema_parity_problems(paths: DataPaths) -> list[str]:
    """Assert the committed DDL still matches the committed contracts.

    The CI job that runs this is the load-bearing half of the Snowflake story:
    it needs no account, costs nothing, and catches the failure that actually
    happens -- a gold table gaining a column while the SQL does not.
    """
    specs = load_specs(paths)
    if not specs:
        return ["no committed contracts to compare against"]

    expected = generate_snowflake_ddl(specs)
    problems: list[str] = []
    for name, contents in expected.items():
        path = paths.sql_snowflake / name
        if not path.exists():
            problems.append(f"{name}: not committed; run `lineupiq snowflake ddl`")
            continue
        if path.read_text(encoding="utf-8").rstrip() != contents.rstrip():
            problems.append(f"{name}: differs from the generated DDL; regenerate and commit")
    return problems
